import "../styles/globals.css";

export const metadata = {
  title: "DALL-E 2.0 Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        {/* Prompt Input */}
        {/* Prompt Input */}
        {children}
      </body>
    </html>
  );
}
